backend/classic_mvc/ministry/ministerio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
]

backend/classic_mvc/ministry/stock/urls.py
from django.urls import path
from .views import (Home, Login,Logout, 
                    CreateUser, Delete_User, List_User, EditUserView,
                    CreateProduct,ListProduct,DataUser,EditProductView,Delete_Product,
                    RegistrarEntrada,CrearRegistroIngreso,EntradaProductoView,ListEntradaProducto,EditEPView,Delete_EP,
                    CategoriasView,ListCategorias,Delete_Categoria,EditCategoriaView,
                    CreateDeposito,ListDeposito,Delete_Deposito,EditDeposito,
                    CreateArea,ListArea,Delete_Area,EditAreaView,
                    CreatePatrimonio,ListPatrimonio,Delete_Patrimonio,EditPatrimonio,
                    CreateSede,ListSede,Delete_Sede,EditSedeView, crearRQ, FiltrarProductosView, confirmar_view,
                    CreateRQ,ListRQ,DeleteRQ,EditRQView, createPersona
                    
                   )
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
from .forms import (PassReset, PassConfirm)

urlpatterns = [
    # /Login and home/ 
    path('',Login.as_view(), name='login'),
    path('home', Home.as_view(),name='home'),
    path('logout/',Logout.as_view(), name='logout'), 
    # / User/
    path('createuser/',CreateUser.as_view(), name='createuser'),
    path('deleteuser/<int:pk>/', Delete_User.as_view(), name='deleteuser'),
    path('listuser/', List_User.as_view(), name='ListUser'), 
    path('edituser/<int:pk>/',EditUserView.as_view(),name = 'edituser'),
    path('data_user/<int:pk>/', DataUser.as_view(), name='datauser'),
    # / Reset password /
    path('pw-reset/', PasswordResetView.as_view(template_name='registration/password_reset_form_custom.html', form_class=PassReset), name = 'password_reset'),
    path('pw-reset_confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm_custom.html', form_class=PassConfirm), name = 'password_reset_confirm'),
    path('pw-reset_done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done_custom.html'), name = 'password_reset_done'),
    path('pw-reset_complete/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete_custom.html'), name = 'password_reset_complete'),
    # / Productos /
    path('create_product/',CreateProduct.as_view(template_name='productos/create_product.html'), name='createproduct'),
    path('listproduct/', ListProduct.as_view(), name='listproduct'), 
    path('deleteproduct/<int:pk>/', Delete_Product.as_view(), name='deleteproduct'),
    path('editproduct/<int:pk>/',EditProductView.as_view(),name = 'editproduct'),
    path('registrar_entrada/', RegistrarEntrada.as_view() , name='registrar_entrada'),
    path('crear_registro_ingreso/', CrearRegistroIngreso.as_view(), name='crear_registro_ingreso'),
    # / Entrada de Producto /
    path('entradaproducto/', EntradaProductoView.as_view(), name='entradaproducto'),
    path('listentradaproducto/<str:producto_nombre>/', ListEntradaProducto.as_view(), name='listentradaproducto'),
    path('deleteentradaproducto/<int:pk>/', Delete_EP.as_view(), name='deleteentradaproducto'),
    path('editentradaproducto/<int:pk>/',EditEPView.as_view(),name = 'editentradaproducto'),
    # / Area /
    path('createarea/',CreateArea.as_view(), name='createarea'),
    path('listarea/', ListArea.as_view(), name='listarea'), 
    path('deletearea/<int:pk>/', Delete_Area.as_view(), name='deletearea'),
    path('editarea/<int:pk>/',EditAreaView.as_view(),name = 'editarea'),
    
    # / Deposito /
    path('listdeposito',ListDeposito.as_view(),name = 'listdeposito'),
    path('editdeposito/<int:pk>/',EditDeposito.as_view(),name = 'editdeposito'),
    path('deletedeposito/<int:pk>/',Delete_Deposito.as_view(),name = 'deletedeposito'),
    path('createdeposito',CreateDeposito.as_view(),name = 'createdeposito'), 
    # / Patrimonio /
    path('editpatrimonio/<int:pk>/',EditPatrimonio.as_view(),name = 'editpatrimonio'),
    path('deletepatrimonio/<int:pk>/',Delete_Patrimonio.as_view(),name = 'deletepatrimonio'),
    path('createpatrimonio',CreatePatrimonio.as_view(),name = 'createpatrimonio'),
    path('listpatrimonio',ListPatrimonio.as_view(),name = 'listpatrimonio'), 
    # / Categorias /
    path('createcategorias/', CategoriasView.as_view(), name='createcategorias'),
    path('editcategoria/<int:pk>/',EditCategoriaView.as_view(),name = 'editcategoria'),
    path('deletecategoria/<int:pk>/', Delete_Categoria.as_view(), name='deletecategoria'),
    path('listcategoria',ListCategorias.as_view(),name = 'listcategoria'), 

    # / Sede /
    path('createsede/',CreateSede.as_view(), name='createsede'),
    path('listsede/', ListSede.as_view(), name='listsede'), 
    path('deletesede/<int:pk>/', Delete_Sede.as_view(), name='deletesede'),
    path('editsede/<int:pk>/',EditSedeView.as_view(),name = 'editsede'),
    
    
    # / RQs /
    path('crearRQ/', crearRQ.as_view(),name = 'crearRQ'),
    path('filtrar_productos/', FiltrarProductosView.as_view(), name='filtrar_productos'),
    path('confirm_view/', confirmar_view, name='confirm_view'),
    
    path('createrq/',CreateRQ.as_view(), name='createrq'),
    path('listrq/',ListRQ.as_view(), name='listrq'),
    path('deleterq/<int:pk>/', DeleteRQ.as_view(), name='deleterq'),
    path('editrq/<int:pk>/',EditRQView.as_view(),name = 'editrq'),
    path('create_persona/', createPersona.as_view(), name='create_persona'),

]

backend/classic_mvc/ministry/stock/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group

class UserManager(BaseUserManager):
    def Create_user(self,username,password=None):
        if not username:
            raise ValueError('Usuario invalido')
        usuario  = self.model(username=username)
        usuario.set_password(password)
        usuario.save(using=self._db)
        return usuario
    

    def create_superuser(self,username,password):
        usuario = self.Create_user(username=username, password=password)
        usuario.is_superuser = True
        usuario.is_staff = True
        usuario.is_active = True
        usuario.save(using=self._db)

        return usuario
    
#crea los campos en la base de datos
class Usuarios(AbstractBaseUser, PermissionsMixin):
  username=models.CharField(max_length=25, null=True, unique=True)
  first_name=models.CharField(max_length=25, null=True)
  last_name=models.CharField(max_length=25, null=True)
  dni=models.IntegerField(null=True)
  email=models.EmailField(null=True)
  is_active=models.BooleanField(default=True)
  is_staff=models.BooleanField(default=False)
  is_superuser=models.BooleanField(default=False)
  date_joined=models.DateTimeField(auto_now_add=True)
  last_login = models.DateTimeField(default=timezone.now)
  groups=models.ManyToManyField(Group , related_name='usuarios')
  sector = models.CharField(max_length=25, blank=True, null=True)

  objects = UserManager()

  USERNAME_FIELD = 'username'
  REQUIRED_FIELDS = []

  def __str__(self):
    return self.username



class User_compras(models.Model):
    username_compras=models.ForeignKey(Usuarios, on_delete=models.CASCADE)
        

    def __str__(self):
        return self.username_compras

class User_deposito(models.Model):
    username_deposito=models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    def __str__(self):
        return self.username_deposito
    


class Deposito(models.Model):
   nombre=models.CharField(max_length=25,blank=True, unique=True)
   direccion=models.CharField(max_length=25,blank=True, unique=True)
   observacion=models.TextField(blank=True)
   registrado_por = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
   def __str__(self):
    return self.nombre

class Area(models.Model):
   nombre=models.CharField(max_length=25,null=False, unique=True)
   responsable=models.ForeignKey(Usuarios, on_delete=models.CASCADE)
   def __str__(self):
    return self.nombre

class Sede(models.Model):
   nombre = models.CharField(max_length=25, null=False,unique=True)
   direccion = models.CharField(max_length=25, blank=True,unique=True)
   observacion = models.TextField(max_length=30,blank=True)
   nombre_area = models.ForeignKey(Area, on_delete=models.CASCADE)
   
   def __str__(self):
    return self.nombre




class Categorias(models.Model):
   nombre=models.CharField(max_length=25, null=False,unique=True)
   descripcion=models.CharField(max_length=25, blank=True)
  
   def __str__(self):
    return self.nombre

 

class Producto(models.Model):
    nombre=models.CharField(max_length=25, null=False,unique=True)
    categoria=models.ForeignKey(Categorias,
    on_delete=models.CASCADE)
    descripcion=models.CharField(max_length=25, blank=True, unique=True)
    cantidad_minima=models.IntegerField()
    observacion=models.TextField(blank=True)
   
    def __str__(self):
        return self.nombre
    
    def calcular_cantidad_total(self):
    # Calcular la cantidad total sumando las cantidades de las entradas relacionadas
        return sum(entrada.cantidad for entrada in self.entradaproducto_set.all())

    calcular_cantidad_total.short_description = 'Cantidad Total'
   
class EntradaProducto(models.Model):
    numero_remito=models.IntegerField()
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    ubicacion=models.ForeignKey(Deposito, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    Unidades_de_Medida = [
        ('kg', 'Kilogramo'),
        ('g', 'Gramo'),
        ('l', 'Litro'),
        ('ml', 'Mililitro'),
        ('U', 'Unidad')
         ]
    unidadmedida = models.CharField(max_length=10, choices=Unidades_de_Medida, default='Unidad', null = True)
       
    fecha_ingreso = models.DateField()
    fecha_vencimiento = models.DateField(blank=True, null=True)
    observacion=models.TextField(blank=True)
    
    def __str__(self):
        return f"Entrada para {self.producto.nombre} - Cantidad: {self.cantidad}."

class RegistroIngresoProducto(models.Model):
    username = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    entradas_productos = models.ManyToManyField(EntradaProducto)

    def __str__(self):
        return f"Registro por {self.username} el {self.fecha_registro}"



# class Estado_RQ(models.Model):
#      estados = [
#          ('Pendiente','Pendiente'),
#          ('En Proceso', 'En Proceso'),
#          ( 'Finalizado','Finalizado'),
       
#      ]
#      estado_rq = models.CharField(max_length=10, choices=estados, default='')
     
#      def __str__(self):
#             return self.estado_rq
   
      
####################################################################################################################
class Persona(models.Model):
   nombre = models.CharField(max_length=25, blank=True)
   apellido = models.CharField(max_length=25, blank=True)
   direccion = models.CharField(max_length=25, blank=True)
   localidad = models.CharField(max_length=25, blank=True)
   telefono = models.IntegerField()
#    observacion = models.CharField(max_length=100, blank=True)

class RQ(models.Model):
    fecha = models.DateField()
    destinatarioSyN = [
       ('----', '----'),
       ('Sede','Sede'),
       ('Persona','Persona')
        ]
    destinatario = models.CharField(max_length=25, choices=destinatarioSyN, default='----')
    # sede = models.ForeignKey(Sede, on_delete=models.CASCADE)
    # persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    

    estados = [
         ('Pendiente','Pendiente'),
         ('En Proceso', 'En Proceso'),
         ('Finalizado','Finalizado'),
            ]
    estado_rq = models.CharField(max_length=10, choices=estados, default='Pendiente')
    
    nota_gedeba = models.CharField(max_length=10)
    remito = models.CharField(max_length=10)
   
    
    
   


   
#    def save(self, *args, **kwargs):
#         if not self.pk:  
#             super().save(*args, **kwargs)  
#             producto = self.nombre_producto
#             cantidad = producto.cantidad
#             producto_nombre = self.nombre_producto.nombre
#             fecha_str = self.fecha.strftime('%Y-%m-%d')
#             self.nombre = f"RQ-{producto_nombre}-{fecha_str}"

#             try:
#                 producto.restar_stock(cantidad) 
#             except ValueError:
#                 # 
#                 raise ValueError('No hay suficiente stock disponible.')

#             super().save(*args, **kwargs)  
#         else:
#             super().save(*args, **kwargs)
    
#    def __str__(self):
#         return self.nombre


#####################################################################################################
   

# class Estado_P(models.Model):
#    estados = [
        
#         ('D','Disponible'),
#         ('P','En prestamo'),
#         ('B','Baja'),
       
#     ]
#    estado_p = models.CharField(max_length=10, choices=estados, default='Disponible')
#    def __str__(self):
#     return self.estados
   


class Patrimonio(models.Model):
   nombre = models.CharField(max_length=25, blank=True)
   descripcion = models.TextField(max_length=25, blank=True)
   cantidad = models.IntegerField()
   ubicacion = models.ForeignKey(Deposito, on_delete=models.CASCADE)
   f_ingreso = models.DateTimeField()
   estados = [
        ('Disponible','Disponible'),
        ( 'Baja','Baja')
        
           ]
   estado_p= models.CharField(max_length=10, choices=estados, default="Disponible")
   Acta_Admin_Baja_N = models.CharField(max_length=10, blank=True)
   observaciones =models.TextField(blank=True,max_length=150)
   
   def __str__(self):
      return self.nombre
   

   

      

backend/classic_mvc/ministry/stock/templates/categorias/createcategorias.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}

<script src="{% static 'funciones.js' %}"></script>


<div class="card registration-card mb-1">
    <div class="card-body">
        <h6 class="registration-title mb-4">Nueva Categoría</h6>

        <form action="" method="post">
            {% csrf_token %}
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 mb-3">
                    <div class="d-flex flex-column">

                        <label for="nombre">Nombre</label>
                        {{ form.nombre }}

                        <label for="descripcion">Descripción</label>
                        {{ form.descripcion }}
                       
                    </div>
                    {% if form.errors %}
                        <div class="invalid-feedback-custom">
                            {% for field in form %}
                              {% for error in field.errors %}
                                <p class="error">{{ error }}</p>
                              {% endfor %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="d-flex justify-content-end mt-4">
                <div class="d-flex">
                    <a class="btn btn-user-cancel mx-1" type ="reset" href="{% url 'createproduct' %}">Volver</a>
                    <button class="btn btn-user-success mx-1" type="submit">Guardar</button>
                </div>
            </div>
        </form>

        <div class="popup-container" id="popup-container">
            <div class="popup-content">
                <p id="error-message" class="error-message"></p>
                <button id="close-popup" class="close-popup">Cerrar</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Categoría</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <label for="id_nombre">Nombre:</label>
        <input type="text" name="nombre" id="id_nombre" value="{{ categoria.nombre }}">
        
        <label for="id_descripcion">Descripción:</label>
        <input type="text" name="descripcion" id="id_descripcion" value="{{ categoria.descripcion }}">
        
        <button type="submit">Crear</button>
    </form>
</body>
</html>

backend/classic_mvc/ministry/stock/templates/categorias/deletecategoria.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}

<div class="card delete-user-card">
    <div class="card-body">
        <form action="" method="post" class="d-flex flex-column delete-user-form">
            <div class= "text-center delete-menu-text">
                ¿Está seguro que desea borrar la categoria?
                {{Categorias.nombre}}
            </div>    
            {% csrf_token %}
            <div class= "d-flex justify-content-center delete-menu-btn">
                <a class="btn btn-user-cancel mx-4 btn-mw" href="{% url 'listcategoria' %}">Volver</a>
                {% comment %} <div class="ml-auto"></div> {% endcomment %}

                <button type="submit" class= "btn btn-user-success mx-4 btn-mw">Eliminar</button>
            </div>
            
        </form>
    </div>
</div>
    

{% endblock %}

backend/classic_mvc/ministry/stock/templates/categorias/editcategoria.html
{{form.as_p}}

backend/classic_mvc/ministry/stock/templates/categorias/listcategoria.html
{%for Csategoria in object_list%}
    
   {{Categorias}}

{%endfor%}